name: Simple workflow
on:
  push:
    branches: main

jobs:
  build:
    runs-on: linux
    steps: 
      -uses: actions/checkout@v2
      -name: run a online script
      run: echo Hi this is simple workflow
         
